### ISSUE TITLE
FYI - Second Bed 

### ISSUE THREAD

**Issue by 400HPMustang** [DeeeeLAN/homebridge-sleepiq#24]
Definitely not an issue but an FYI. I recently ordered a second bed, a new M7. Still no fancy features like foot warmer, lights or adjustable base but by the time it took me to get from the store to home the new "bed" was showing up in homekit with a 50% firmness on both sides. It seems like as soon as you buy the bed the API recognizes that there is another bed on your account. I haven't tried to change any of the settings on the new bed as I won't have it until after my remodel is done but it's just worth noting that a "phantom" bed will show up automatically. It caught me off guard at first that the API seems to reflect it right away.

**Comment by DeeeeLAN** [comment]
I assume this is because I pull your bed options from your account, not your local network. I am surprised your account updated so quickly but still kind of cool. I did write the plugin to automatically detect multiple beds, but obviously have not tested controlling them. Hopefully everything is smooth but definitely report any weird issues you run into.
