### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by 64Spaces** [DeeeeLAN/homebridge-sleepiq#7]
Some general syncing observations:

```
                                  Sleep #     Bed Position
Sleep Number Remote --> iOS App     Yes        Yes
Sleep Number Remote --> HomeKit     No         No

HomeKit--> iOS App                  Yes        Yes
HomeKit--> Sleep Number Remote      Yes        Yes

iOS App--> HomeKit                  Yes        No
iOS App--> Sleep Number Remote      Yes        Yes
```

**Comment by 400HPMustang** [comment]
I've seen this as well, that if you manipulate your sleep number with the iOS app the remote is incorrect and the bed must be set back to 100 by the remote and then set to your correct sleep number again OR you have to forgo the remote completely and just use the app.

**Comment by DeeeeLAN** [comment]
So are you saying they have issues completely within their system outside of my code as well? 

It has been a little while since I looked at the code so my memory might not be right, but I am a little surprised there is any case where the sleep number is out of sync because it pulls directly from their server every few seconds. 

It makes me wonder if the remote is changing things locally and not updating the server, but for the remote app to match that doesn’t make sense. That is a weird case. Unfortunately, I never got a remote, so I can’t test it at all. 

I would have to check on the bed position not updating. I thought that gets fetched at the same time as the sleep number so it should update too, but maybe it isn’t happening that way after all. Again, hard for me to test since I don’t have a base.

**Comment by 400HPMustang** [comment]
I don't have a base either I'm just talking about the firmness setting. Whatever is going on, I just tried to replicate it and the remote, Homebridge, Homekit, and the native iOS app all reflect accurate sleep numbers. The only thing odd now is I've been out of the bed for a solid 5 minutes and the bed thinks I'm in bed.

**Comment by 64Spaces** [comment]
Generally, I now believe everything is syncing properly. My observations might be off. I will double check them. Sometimes the “occupancy” does get “stuck”, but I think it’s on the bed side, not the plugin.

**Comment by DeeeeLAN** [comment]
I have noticed the occupancy can be a little flaky as well. I think that is there fault. I read the value they output every 5 seconds and display it, so there isn't much I can do. For now I will close this ticket. If you are able to rediscover any syncing issues, feel free to re-open it.
