### ISSUE TITLE
Verified split king works

### ISSUE THREAD

**Issue by macjbraun** [DeeeeLAN/homebridge-sleepiq#9]
I have the double twin xl bed. I can confirm it works as advertised. It would be nice to get a notification when someone gets out of bed. This plugin is great. You homebridge developers are really helping the smart home movement. I wish someone would create a plugin that would allow me to control any Alexa device from homekit.

**Comment by DeeeeLAN** [comment]
Looks like you can get at least all the devices that homekit recognizes through alexa here: https://www.npmjs.com/package/homebridge-Alexa

Thanks for confirming it is working. Homekit has built-in notification support. Just open the side sensor settings in the home app and turn on the slider for notifications. It should ping your phone every time that accessory changes state after you do that.

**Comment by macjbraun** [comment]
Homebridge-Alexa exposes homebridge/HomeKit devices to Alexa. I would like to control Alexa devices from homekit. 

I turned notifications on and I get notified when I get in bed but not when I get out. 

Thanks for the great work.

**Comment by DeeeeLAN** [comment]
Ah, yes, I did not read closely enough. It looks like there is s package available to control Alexa from the command line: https://github.com/thorsten-gehrig/alexa-remote-control, but I am not sure how well it works. In theory, it could be used with homebridge, at least in part. 

The notifications thing is at Apple's level, so I Don't think there is much I could do about it. I mean, you could inverse the occupancy status in the plugin, then it would notify you when you got out of bed but show you as out of bed when you were in bed. If you wanted to do this, it would be simple to fork the code and add it for yourself. Otherwise, the route I would probably take is set up an automation so that when there is no occupancy, a light gets turned on, and the light can be tied to a notification maybe (A fake light through homebridge would work well for this). Or I don't know if IFTTT supports homebridge sensors as sources. Then you could just have IFTTT send you a notification. Last I looked into it, they just supported buttons being sent to homebridge, but maybe they have added more.
